name: CI

on:
  push:
    branches: [master]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 12.x

      # Instalar as dependências npm/yarn
      - name: Install dependencies
        run: yarn

      # Executar o build da aplicação
      - name: Run build
        run: yarn build

      # Copiar todo código para Digital Ocean
      - name: Copy Dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: '.,!node_modules'
          target: '~/app/gobarber-backend'

      - name: Install all dependencies on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd ~/app/gobarber-backend
            yarn
            ./node_modules/.bin/typeorm migration:run
            pm2 restart gobarber-api
